spring:
  datasource:
    username: root
    password: zhj123459
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&allowMultiQueries=true
  redis:
    host: 192.168.160.128
    port: 6379
    database: 0
    password:
  application:
    name: education
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8089
security:
  encryptRSAKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAIBS+fndE8Iy8jtqNCzF1Xl3PBnIwBC+1RXj7ehu59XxRaOs69F0zeBOA4vQ5LlnxkXZfjCKWzQcy9tql4orAaLy96eiM0aqdd2UKub08A0LPQFZfEVGTCFkHgwSmKCnzDAx/Lgblx9VjbgEuNVWuMuBAdvlXC32jWGioKL4YBWrAgMBAAECgYBTS4kPcz1cFQ2/G1T6qv/CdG8CnZhuRjCyoNzQvwylhpMZhykbMKJiMsGCg/mzj3TX6jFK+MPys65vomTzPq80UwYM6EB8LsjpOyOrFqaCMyFxdWByRmMgmzUGRLf7xSR2OIKDcZTXEcXkIwZLCzYMAKRVqBRdZah4cptecE/KgQJBANoIL7l6UkSwh9zLqvTQ2RUnEKkKyD20NVyOdmaztsR7/YpSmpdY0n3eqCbNy0kwkpWPBVr1Yo3LOIORx9zmgbECQQCWq6KrkpUH4rOw5DEVB8a9OyawSZR8dwvi15LSDtfaBTHtTIBs9uyjIUssZomZNlYBhSSBb06WJV7auGKJCOgbAkAOOA50uCd5V1Hk8ltZz+z4Vi3d+FgKvh/kw12xYPMAaV2lkbGHQUGo98ZbkXw6b7J/km40+l/NA33SBsXUACxhAkA9h0u/uvVnKfntc9JjXzCWmDA9b17W0RqmgRgw9eTJ4LM5z7LmTJPoLjFvqVPpoFnQ9xkoTlcOU6Z/tSpwAZYfAkANqW84gt7OfdP+WWaJxVpEp5B2bIS+NPUfozkomNOcRxsfKUvZKkFQO95jRY/Nc00Ceph9G8QLs47+RXCZC2/M
  encryptJWTKey: emhqMTIzNDU2Nzg5MTAxMTEyMA==
  accessTokenExpireTime: 3000
  refreshTokenExpireTime: 18000
#日志配置 无特殊需求无需更改
logging:
  config: classpath:log4j.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG
education:
  uploadFile:
    filePath: D:/educationFile/
    filePathUrl: http://127.0.0.1:8089/api/upload
aliyun:
  oss:
    file:
      endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
      accessKeyId: "LTAI5tAUqSobwA3iSJahrvEK"
      accessKeySecret: "zul8WPqOuZHXA2U3DMx5zlBs8CtvQ6"
      bucketname: "edu-firstly"


